# Generated by Django 5.2.5 on 2025-09-06 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_tags_alter_scope_is_main'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'ordering': ['-is_main']},
        ),
    ]
